### PR TITLE
Add yoshida6 integrator

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Yoshida6 is a symplectic integrator similiar to PEFRL in structure but it is of order 6 instead of 4. So for long time simulations this may be a better choice. 🚀 I also refactored the PEFRL code so I could reuse it for this as well.

I'm starting to run out of ideas for new integrators 😅 do you miss any special one? Everything after RKN12 feels so tame 🤣

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀  Sweet!!! 

I'm trying to figure out how to implement co rotating reference frames, but I'm not getting it quite right. It's a feature I have to implement, though, since I want to be able to visualise things like horseshoe and tadpole orbits! 

Have you read this [paper](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20080034886.pdf)? Found it to be an interesting read. 

There's always Barnes Huts, but from what I understood on the basis of what you told me implementing Barnes Huts is no trivial matter... I don't know if there are other physics aspects of Harmony of the Spheres that you would be interested in working on, but if that's the case let me know and I have a very long list of stuff that I want to implement 🤣 . Feel a bit bad, though, because since I started my new job I've barely had time to put aside for my little baby and I very much feel like the dad that went out to buy cigarettes only to never return. 

Trying to get something done every weekend, though... A lot of bricks make for a house, or something along those lines 🤣

**Comment by HugoGranstrom** [comment]
Horseshoes and tadpole orbits sounds interesting ;-) what is the difference between a ordinary rotating reference frame and a co-rotating one?

That was quite the read, it seems like it would be a good idea but it also seems a bit complicated to implement 😅 NASA really has some cool documents available 📃

Barnes Hut is still a future quest for me sadly 😅 could take a look at it again but it feels like the vector implementation is needed first. If you have anything else that needs to be added I would be pleased to help you 😉

It's hard to get the time to work on your hobbies sometimes sadly. It's amazing how people can maintain open source software on their spare time really. 🏗️ Many bricks do indeed make a house, or just a pile of bricks if your unlucky 😂

**Comment by TheHappyKoala** [comment]
In a rotating reference frame you hold one body fixed; this is what lets you observe the solar system unfold from the point of view of Earth in the The Sun and the Earth Moon System scenario, for instance. When Earth is the rotating reference frame, the sun appears to orbit it... This just so happens to be the reference frame you and I find ourselves in in reality 🤣 In a co rotating reference frame both bodies are held fixed, which is akin to your camera is rotating at the same velocity as, for example, Earth is. Earth in this frame will only be fixed around one axis, though, so you will see it moving ever so slightly, which is of course due to the fact that Earth's orbit is not a perfect circle, but an ellipse, and the movement you see is the difference between the periapsis and apoapsis of Earth's orbit. Does that make any sense whatsoever? If not, do poke me with a stick and I'll try to do a better job explaining it 🤣 !

Decided to leave that feature for now (when I do the solution usually comes to me a week or two later 👯‍♂️ ) and implement some barycenter stuff. Not sure why I hadn't done that earlier, but you can now see the barycenter of a system of masses, and you can turn it off in the graphics tab, and set it to be the focus of the camera. Tomorrow I'm gonna enable the user to get the barycenter between two bodies, so that you can set it to the barycenter of the pluto charon system, and watch how they orbit a point that is outside both bodies, which is pretty cool. That's why there's not Pluto system scenario yet... Wouldn't do it justice without being able to set the camera focus to the bary center of the system! 

Uh, I'm tired, need to sleep, but now I have a very strong reason to start working on implementing a nicer way of working with vectors 🤣 

I don't know if you'd be interested in working on improving the debris clouds that are produced by a collision, but if you are, they most certainly need a lot of work 🤖  (I mean, apollo 11 crashing into Earth in the free return trajectory scenario produces an epic debris cloud lol). It would also be cool be able to detect when a collision destroys both bodies and just produces one big cloud of debris... Arrhhh... I have too many ideas, and I want to implement them all... 

Getting up at six tomorrow, though... So off to bed it is to dream about galaxies colliding and planets we do not yet know of 🌍 .

**Comment by HugoGranstrom** [comment]
That sounds like quite the handful, but it makes sense ;-) 

Right, Charon isn't as much of a moon as it is a little brother to Pluto. It's fascinating that so "small" bodies can orbit each other. 

🤣 Apollo 11 is quite the beast here. I will take a look at it 😉 Graphics isn't my expertise but I will take a look at the code and see if I can get my head around it :-D it will be a good learning experience otherwise.

I have a bad habit of coming up with ideas when I'm trying to sleep so sleeping on a problem really helps me. Will try it now :sleep

**Comment by TheHappyKoala** [comment]
Yay... Here's [Pluto & Friends](https://thehappykoala.github.io/Harmony-of-the-Spheres/#/scenario/The%20Sun%20and%20the%20Plutonian%20System)!

Ah, I was thinking more about the calculations that go into determining the trajectories of the particles that are produced by collisions... Taking things like the angle of the impact, the energy released and so on into account. 

Come to think of it, I need to implement [Roche limits](https://en.wikipedia.org/wiki/Roche_limit), too 🔥 

Gonna look into shoring up how we work with vectors, first, though... I'm gonna make it a class with the name of H3... Will ping you when I have something tangible that you can look at/have opinions about 🤣 🚀 🐨

**Comment by HugoGranstrom** [comment]
That's a cool sim ;-) didn't know Pluto had so many things orbiting it 😄 

That sounds more like my ballpark 😅 I'll take a look into it. What is the current way you're doing it in?

Roche limits sound cool, are you planning on setting a cloud of particles in orbit at that radius?

I'll be looking forward to the vectors ;-D

**Comment by TheHappyKoala** [comment]
Yea... Pluto has five buddies!  One thing I hadn't realised until I ran this sim was how tilted the Plutonian system is relative to the ecliptic: almost 90 degrees! So the Plutonian system moves around the sun pretty much like a rolling wheel, much like Uranus and its moons do. 

The current way I'm doing it is way fugly and I wouldn't ask you to even touch that code, but the good news is that I've finally created a refactoring branch... Gonna tidy things up once and for all so that working with the code base is more enjoyable. This involves creating a module for vectorgans; you can look at the start of it [here](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/commit/779c85c22b5550f51d0ea159f2830018e6ab1ec8). If you don't have any major objections, my intention is to make it the base class of all the integrators and pretty much any class that deals with vectors in one way or another. This means I'll also refactor the physics utils module into a class, which will make more sense, at least to me. Already refactored the label code and encapsulated it in a class which you will find in the refactoring branch. 

If you see any WTF's in the vector module, let me know before I do too much work on it 🤣 ! What's there already should make working with vectors way more enjoyable than it has been up until now. 

Regarding the Roche limit, yea, that's pretty much the idea... Well, you'd have particles falling off gradually and the mass of the body decreasing accordingly. Need to do some more reading on this, but before I continue with my spacecraft, roche limits or flying koalas, I need to tidy things up and restore order 🤣 🐨

**Comment by HugoGranstrom** [comment]
Now when you say it, it does really roll around the sun, that would make it easier to spot all of them, I imagine. 

The vectors look slick 😉 It will make it much more pleasurable to work with them :-D

It already looks a lot cleaner ;-)

**Comment by TheHappyKoala** [comment]
Holy guacamole... I've refactored pretty much all of integrators; could you please take a look at the refactored versions and let me know if it all looks okilidokili? And if you have feedback, please shoot!  Did some sanity checks, but a second pair of eyes much would be much appreciated :D. I can still make some improvements by changing how vector data is structured, as in restructuring it to v.p = {x, y, z} and v.v = {x, y, z}... I'll write a script and do that next week. 

Done some other refactoring, too, but there's still a lot of work to be done. Having fun doing it, though, and it's a good mental exercise: refactoring the integrators gave me a better what's going on . 

Will probably afford myself the luxury to work on a feature now, though... 🤣 !

**Comment by HugoGranstrom** [comment]
Wow that's quite the refactoring ;-D The only thing that don't seem to work is the RKF integrator. 

Haha you noticed my terrible code 🤣 

Can't wait to see which feature you're adding next 😉

**Comment by TheHappyKoala** [comment]
Hahaha... Dood, I love your code! I felt kind of shitty touching it, but I would have felt even shittier going all like... Hey, here is a new way of working with vectors, please refactor the contributions you made in your own spare time! 

Regarding the RKF, oops, forgot about that one, but will fix it tomorrow. Tomorrow or on Saturday I'm hoping to add basic support for trajectory correction maneuvers, starting with a simulation of Mavens hohman transfer to Mars and subsequent orbital insertion; wouldn't have been possible without your pretty, pretty integrators with adaptive time steps, so yay, thank you, once again :smile: ! With this feature we can simulate pretty much any space mission for which JPL has data!!!! Cassini's tour of gravity assists in the inner solar system that got it to Saturn, Juno's trip to Jupiter and even Dawn's trip to Vesta and Ceres!!!! This is just the start, though, of the spaceflight stuff I have in mind, but I figured I'd start out easy and get something rolled out. 

Work, tomorrow, though... So time to zzzZZzzZZzzz

**Comment by HugoGranstrom** [comment]
That sounds awesome :-D How are you implementing it? Do you set a date at which a bit of extra acceleration is added to the spacecraft? Or is it more complex?

**Comment by TheHappyKoala** [comment]
Hey Hugo!

Sorry for taking my sweet time to get back to you, but to answer your question, yes, right now that's what I'm doing - instantaneous changes in acceleration! I have something a bit fancier in the pipe line, but there is a lot of stuff that needs to get before it would make sense to introduce the fancier stuff. The next step will be to write a layer for this service: https://trajbrowser.arc.nasa.gov/traj_browser.php - didn't even know it existed until a few days ago, but it opens up a whole universe of possibilities as far as simulating cool stuff and trajectories goes. Idea is to integrate it into Harmony of the Spheres as a trajectory planning tool. 

There's a Hohmann trajectory scenario online, but the one I'd really like you to check out is this one: 

https://thehappykoala.github.io/Harmony-of-the-Spheres/#/scenario/Europa%20Clipper%20-%20Hohmann%20Transfer%20to%20Jupiter

A simulation of the journey of the Europa Clipper mission to Jupiter in June 2022 :rocket: !!! 

In the process of working on that scenario I started developing the seed of an event system, which I think will open up possibilities visualisation and story telling wise... Take a look at the scenario and I'm sure you'll see what I'm getting at :alien: ! 

Happy Easter and I hope you're enjoying the good weather!!! :sun_with_face:

**Comment by HugoGranstrom** [comment]
I've been taking a break from coding during my Easter break so it was a well-planned silence from your part 😉 How many instantaneous changes in acceleration would you say is used during a Hohmann transfer? Is it just in the beginning and end or continuous? It was a really cool simulation 🚀 although I became a bit confused what I was looking at when it changed perspective 😅 but when I realized what I was watching it blew my mind! 💥 I noticed that you used Nystrom6 as integrator, I'm generally interested in the pros and cons of integrators so I'm wondering what your reason was for using it over RKN12 or Yoshida6. Was it for visual reasons to get a smoother animation with a constant timestep or did you notice any differences in accuracy? 😄 

Nasa really has alot of cool stuff available to the public!!! 😲 That will really be cool to have. It has huge amounts of data. Have you been thinking about adding JPL's Horizon Ephermis? I think it would be a cool idea if one could give a date and a list of bodies and then it loads them and starts the simulation. But maybe that is a bit complicated... I was scared away when I read "telnet" 🤣 .

The event system seems to work fine ;-) What was the trigger in the Mars Hohmann transfer? The distance to Jupiter? Now I'm starting to imagine a whole documentary with textboxes and voices being activated when a user controlled spacecraft begins to approach a planet 😅 All in Harmony of the Spheres 🎥 Maybe I'm a bit too far in the future.

**Comment by HugoGranstrom** [comment]
And happy Easter to you too 🐰 🥚 🍬 The weather has really been amazing this week! 🌞

**Pull request merged**
