### PR TITLE
fix: stop the universe from imploding because of 0 / 0

### PR DESCRIPTION
**Pull request by TheHappyKoala**

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Seems to work, but just in case it would be sweet if you could take a look at the commit in question

**Comment by HugoGranstrom** [comment]
Was such a long time since I wrote this 😅 Does 1 / Infinity equal 0 in JS or is it NaN? Did you get errors because of 0/0? What would happen now if r === 0.0 (or is it even possible)?

**Comment by TheHappyKoala** [comment]
0 / 0 gives you infinity, and then when you try to calculate the force exerted between two particles separated by infinity you get NaN galore 🤣 

Quick question. Is there a reason for why there are 8 trees and not 4, 6 or say 12?

**Comment by TheHappyKoala** [comment]
r === 0 or 0.0 doesn't work, because the getLength method spits out Infinity which, as I learnt yesterday, is an actual value of type number in JavaScript 🤣

**Comment by HugoGranstrom** [comment]
Oh my... 😵😂 but I must be blind 🤦‍♀️ I can't find where we divide anything before we do the `const acc = .....` . getLength doesn't do any division and all above it is just subtractions 😅 time to get a pair of glasses 🤓

The kind of structure we are using is called an octree. The root node is a giant cube and it itself contains 8 subcubes. A 2 level tower with 4 cubes as its base

**Comment by TheHappyKoala** [comment]
No, you're not... I shouldn't code before I've had at least 2 mugs of coffee 🤣 

```
      const rVector = v.subtract(p);
      const r = rVector.getLength();
```

When two particles are in the same place, rVector gives you 0, and then when you try to calculate the square root of 0, you get infinity! So with the if statement checking if r === 0, you never get a hit since we should be checking for Infinity and not 0.

**Comment by HugoGranstrom** [comment]
So sqrt(0.0) == Infinity in JS?😵

**Comment by TheHappyKoala** [comment]
Haha, no, it's 0, but when you calculate the force exerted by mass j on i you get infinity... Newton's singularity. When collisions were yet to be implemented it happened, on occasion, that I would add a mass by accident with a semimajor axis of 0, which would cause the same problem, but that was a while ago, so the infinite acceleration issue if two masses occupy the same position at the same time had completely slipped my mind. 

Merging this guy now 🚀

**Comment by HugoGranstrom** [comment]
I'm feeling really slow minded today 🤣😵 so it's in the `const acc = rVector.multiplyByScalar(....)` the infinity arises because we have 0 both in rVector and r?

**Pull request merged**
