### PR TITLE
added general RKN implementation

### PR DESCRIPTION
**Pull request by HugoGranstrom**
I have implemented the RKN integrators in a more general way now so I can just feed it the coefficients for the method and it works. I'm keeping the old code commented out for now just in case anything weird would start happening. I've also added a general base class for adaptive RKN so now it shouldn't be much of a problem to implement new RKN integrators (just tedious 😅). A smaller side effect is that the code isn't as easy to follow along with in the base classes anymore as there is a skyscraper of nested for loops in it 🤣 But it works!

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Great stuff :D! 

I just pushed a build and tidied up the code for generating vectors for spiral galaxies - still a royal mess - so I will test run your changes tomorrow night 🚀 ! 

The RKN64 is, by the way, the new default integrator... It's amazing stuff and I'm shitting rainbows and glitter just thinking about the next integrator you're going to add 💩 🌈 🤣 

Gonna see if I can commit the UI changes you requested now... Will ping you when I have :D!

**Comment by HugoGranstrom** [comment]
The spiral galaxy looks awesome 🛰 😉 

Nice to hear it worked as expected :-D To cure you from those effects I better get it working soon 🤣 🌈 

As I've said before, no hurry ;-) Looking forward to when it's done though :D

**Comment by TheHappyKoala** [comment]
I'm trying to upload a cool gif...

**Comment by TheHappyKoala** [comment]
Okay, [here](https://gfycat.com/jointclutteredhapuku) we go :rocket: !!! I ran a simulation my old laptop last night of the gas giants and the centaur Chiron, to get an idea of how its orbit would evolve, and it matches what I've read about the dynamics of this particular body pretty well. Next time I'll use the PEFRL, though, as I think Chiron colliding with the Sun at the end is an artefact of the integrator (RKN64) not being symplectic. Let's see how the results differ :rocket: !!!!

**Comment by TheHappyKoala** [comment]
Howdy Hugo!

You've made some awesomely solid contributions to the project and taken it to another level, so I feel it's only right that you're listed as a collaborator with the right to push commits yourself. Let me know if you're able to push to the master branch (not sure I've protected it... dabbled around with the settings left and right 🤣 ), and if you ever want me to do a review of your code, you can just request a review when you open a pull request. 

You can, of course, choose not to accept my invitation, but I think you've shown you're more than capable and most of all deserving of the the privileges that come with being a collaborator. And if you somehow screw up, we can always reset to a previous commit, so don't worry about that 🤣 !

**Comment by HugoGranstrom** [comment]
That's some wild hula hooping :rocket always so cool when the theory is aligned with the "reality" 😀 That's probably a good idea to choose PEFRL when you aren't that interested in the exact path it takes but only what kind of patterns it moves with.

This is a huge honor 😳😄😁 thank you so much for entrusting me with this privilege and responsibility. I will do my best to not let you down, but as you said it's hard to really mess things up with git (version control for the win!) 😅. 
I'm planning on letting the majority of the big stuff be review by you (refactorings like this for example) and maybe only small bug fixes unsupervised 😉

I have my last exam tomorrow, after that I will get to work and try out my new super powers 💥💪 

My first commit will be the RKN12 integrator which I have managed to get working finally and it's freaking awesome!!!! Can't wait to share it with you 🚀🚀🚀

**Pull request merged**
