### PR TITLE
add KahanLi8 symplectic integrator

### PR DESCRIPTION
**Pull request by HugoGranstrom**
I have found a couple of new integrators 😅 and I couldn't resist the urge to add them hehe... 🤣

KahanLi8 is an 8th order symplectic integrator. In my benchmarks it blew both PEFRL and Yoshida6 off the charts so it would be my goto integrator for long-time simulations. 🚀 

The commit-hook did work wonderfully as well 😉 now I can commit without having to be ashamed of my code 🤣

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Woha!!! You broke the #500 commit barrier 🔥 🎉 🎈 💯 💯 💯 💯 💯 !!!!

And yay, very happy to hear that the commit-hook worked out for you. I'm going to add linting and possibly some unit tests, as well, as commit-hooks. Right now I'm working on some TypeScript stuff. More specifically I'm thrashing out types for the THREE.js library that we use for the 3D graphics so that we can bring some sanity to that mess, as well. I apologise for not working on any fancy new features this week, but I kind of feel like by implementing these things we'll prevent a huge technical debt accumulating down the road, and my hope is that our Hugo and Darrell clones in a parallell Universe, where they did not decide to shore up the code base, are well envious of the work we are putting in now as they are fighting bugs and slowly giving up because they can't figure out what does what any longer 🤣 ! 

Yay that you wrote your module in TypeScript! Having said that... Now I'm gonna take a break from the stack work and play around with the fancy new toy you've introduced, and remember that when it comes to integrators MORE IS BETTER 🤣 🚀 🐨 !!!

**Comment by TheHappyKoala** [comment]
By the way... Did the H3 Vector module make sense to you now that you have worked with it???

**Comment by HugoGranstrom** [comment]
I kind of cheated on this one, the structure of this integrator is the same as the PEFRL and Yoshida6 so I just copied your TS 😅 so I don't have much to say sadly.

**Comment by HugoGranstrom** [comment]
500 commits and now we go for 500 more 😉 You are a wise man Darrell, thinking in the long term can be hard to do sometimes, and actually working for the long term is even harder 😀👌 That parallel universe do sound pretty scarry 😂 I'll make sure to use the H3 vector module when I'm starting to do work on BH 😅 but all of these cool new integrators are distracting me 😂😂😂

**Pull request merged**
