### PR TITLE
add Sofspa10 symplectic integrator

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Here you go, a late christmas gift from me 🎅 🎄 🎁

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Ohhhhh.... Thanks 🎅 !!! 

But wow, still have some work to do on the netlify integration

**Comment by TheHappyKoala** [comment]
I'll cherry pick this puppy into the gatsby branch

**Comment by TheHappyKoala** [comment]
Ah, champion, you target the gatsby branch . 😄

**Comment by HugoGranstrom** [comment]
Hehe I thought as this doesn't break anything I could as well merge it into the most current branch 😅 I'm a bit afraid of touching the master branch tbh, because that could screw it up big time for you with merge conflicts when you want to merge the gatsby stuff into it 😅

**Comment by TheHappyKoala** [comment]
Nah, really happy you did that, because I'm working with the Gatsby branch and it will, in not too long, get merged into master, so cheers 😄 ! 

You're a good gitizen, and I'm working on becoming one, too!

**Comment by HugoGranstrom** [comment]
Haha I'm up to too much gitanigans to be a good gitizen 😂 

I've done some more reading up on SPH and it seems like it's basically a n-body simulation with pressure + gravity and we should be able to use our current gravity (Barnes Hut) so it should just be a matter of getting the pressure part done and gluing them together 🚀😄 haven't looked at the equations yet though so it may not JUST be to do that 😂😅

**Pull request merged**
