### PR TITLE
Add rkn64

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Here we go again! 🚀 RKN64 is a adaptive Runge Kutta Nyström integrator and it seems to be on par with RKF as far as I can tell. Sometimes it is faster and sometimes it is slower but it is of 6th order of accuracy so it should be a bit more accurate.

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Beautiful, and congrats on making your first change to the UI code :smile: !! I got distracted and continued working on the galaxy simulation the little time that I had to spare this week, but I have to say I'm quite pleased with the results :space_invader: Have you seen the result? 

I'm gonna run a build to get your new integrator online and then I'm going to get back to the space flight module. 

Also need to get started with tidying up the code base... It's so easy to just want to cram new features into the app, but when you do that without much consideration a tech debt starts building up... That and I love sensible code. Oh well, I'm ranting, now :alien: :rocket: 

Now I'm gonna try out your fancy new integrator :cowboy_hat_face: !

**Comment by HugoGranstrom** [comment]
UI isn't my strongest side, which I think you have nailed so it was thankfully not hard to add it. But I think this is as much as a will touch the UI 😅 

I tried out the galaxy simulation and it looked exactly like I imagine a galaxy collision 😀🌌🚀 How is it different from the "ordinary" simulations? Is there a central mass point in the galaxies or is the mass more spread out?

Yeah, tidying up code isn't the most fun thing to do but it's light-years better than trying to read your own code and not understanding what it's doing 😅 The parts of the code I've dabbled with hasn't brought me to much head scratching 😉

Next up I'm planning on adding another adaptive integrator, as it was easy to integrate with the UI. This time it is a RKN12  of 12th order! :rocket I have no idea how it will do but I suspect it will be quite slow 😂 is there any big changes you are planning in the integrators part of the code during your clean up? 

And another question regarding the UI: do you think there would be possible (and preferably easy) to add a "Experimental/Use at your own risk" submenu to the Physics tab where one could change the dt, max_dt and in the future maybe other things? I imagine it would make it easier for you to fine tune what parameters to set for a scenario and it would make it easier for me to test the integrator without having to recompile the program. It's in no hurry but in the future I think it would be a nice feature to have 😅

**Comment by HugoGranstrom** [comment]
One cool thing I just noticed is how obvious the adaptive time step is in the Lunar Return Trajectory. It really slows the simulation down when Apollo 11 is near the moon 🚀

**Comment by TheHappyKoala** [comment]
Regarding the galaxy scenario, it's just two point masses where the particles don't feel each others gravity. Apparently that's a pretty decent way to model a galaxy, though, since the majority of a galaxy's mass is made up of its dark matter halo. Would like to make the physics a bit more sophisticated than that, though, but it's a start :rocket: !

Happy to hear you haven't found my code too obnoxious to work with, and I have to say when you first submitted the pull request for the Verlet Integrator I was very happy since you followed the pattern I'd implemented for the handling of the integrators :1st_place_medal: . To answer your question, though... Not planning on making any changes to the physics modules, besides the utils module. At some point in time I want to implent a module for dealing with vectors, like we talked about, but it's mostly the scene module and the module that handles the processing of the scenarios that I want to do something about... Just thinking about them makes the hair on my back stand up :rofl:! So go ahead without fear that you will have to refactor anything because I decided to go all bonkers on the physics modules :smile: .

Super excited about the RKN12... For the spaceflight nonsense accuracy will be paramount, and I don't particularly care if the FPS is lowered somewhat if it means I can simulate some cool spacecraft trajectory :rocket: . And the nice thing is that with all of your integrators you have a buffet table of integrators to choose from, so you can always pick the integrator that is most appropriate for the scenario being simulated. 

Regarding implementing another tab; of course! Adding UI stuff is pretty easy since I've written the UI as components that you just pass props, too, so at this point it's just application lego to create a new section. Is it just dt, max and min dt that you want to be configurable now?

**Comment by TheHappyKoala** [comment]
And yes, the free return trajectory scenario with the RKN64 or RKF integrator is just such a joy to behold... Like, on a purely technical level... Amazing :rocket: :earth_africa: :new_moon: !!

**Comment by HugoGranstrom** [comment]
It definitely seems to be a good way to model it ;) adding dark matter in some way would be an interesting. It's quite fascinating that there are so many ways to model the same thing. 

I imagined it would be quite cumbersome for you if I paved my own road in your code so I tried as best as I could to use as much of the work you had already done. Glad it was appreciated 😊 I will go ahead then to try to add the RKN12, and probably fix a more general implementation of RKN integrators so I just have to add a matrix of coefficients instead of copy pasting and changing the entire file. Planning on fixing this on Wednesday 🚀

I'm so much looking forward to seeing some cool spacecrafts zipping through space 😉🚀🚀🚀 🌌 the smörgåsbord of integrators will hopefully continue growing but I feel like I make some of them quite obsolete (like poor euler 😂) when adding new ones 😅 guess it's a good thing with competition amongst the integrators. 

I think those are the only ones at the moment that I'm in need of 😊😃 it seems like the graphics part isn't in need of clean up, it seems really well made 😉

Once you go adaptive there is no turning back 😅😂

**Pull request merged**
