### PR TITLE
added the mighty Barnes Hut

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Here it is!!! 🚀 🎆 🎊 All that's needed before we merge this is the UI. 

I have put two new parameters in the Euler.ts constructor: 
```
useBarnesHut: boolean
theta: number (from 0-5 I think would be a good range)
```

Another issue is the maximum distance allowed in a certain scenario, I have set it to 1000 (AU I presume?) for now but if you can come up with a good solution for that, it would be awesome.

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 

I'm at work, but as soon as I'm back home I'll do my very utmost to wrap up the changes, as rounding off the test scenario and ui changes, that I need to make for all of this to work asap. Started working on these things last night, so hopefully I can have them done tonight or tomorrow and then we can push a sizzling hot build online... 

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 


Okay, back to doing whatever it is I'm supposed to be doing 🤣

**Comment by TheHappyKoala** [comment]
I couldn't stop myself from taking a super quick sneak peek at the code and woza... You need to get your butt into computational astrophysics once you're done with your studies; I smell potential!       

Anyhow, back to work 🤣

**Comment by TheHappyKoala** [comment]
Had like the longest day of all time, but strangely enough - well, so it might sound - coming home to this awesome new piece of code brought me back to my obnoxiously cheery old self in a heart beat... This is just so awesome!!! 

This might sound silly, but I found a few very minor TypeScript errors - they don't even prevent the app from running - and upon seeing them my first instinct was to fix them, but then I got this weird feeling; I don't want to make adjustments to the Mona Lisa; edit your poetry or what have you 🤣 

So, would you like to fix the ehrm, TypeScript typos (lol)? If not, I'll take care of it, but I just felt like I had to check with you first before I added a brush stroke to your master piece. 

Weird, I know, but regardless I'm getting the UI up and bouncing now... Unless something explodes in my face, there should be a UI commit coming really soon...

**Comment by HugoGranstrom** [comment]
The errors shouldn't be any problem as the types are "lost in translation" when converting TS to JS. It has to do with that I wanted to save either of two different types in an array, more specifically I wanted to store either one Masstype or 8 TreeNodeTypes in it depending on how many planets was in that tree. I tried to solve it like this:
``children: TreeNodeType[] | MassType[];``
So functionally it isn't any error in the code, it's just that the type checker/linter doesn't understand what I'm meaning 🤣 😅 

Do you, who knows a great lot more of TS than me if there is a easy way to fix this? Otherwise I can rewrite the code a bit to make it TS-safe in the weekend 😉

**Comment by TheHappyKoala** [comment]
There's a toggle BH control in the physics tab now... So, if I understand things correctly, you can run BH with any integrator, as BH is just concerned with how the acceleration vectors are calculated????

**Comment by HugoGranstrom** [comment]
Awesome! Did you fix my temporary values in Euler.ts? 

That is correct ;-) No further changes needed

**Comment by TheHappyKoala** [comment]
Oh, need to add Theta, too... Coming right up

**Comment by TheHappyKoala** [comment]
Noops, not yet... Will take care of that once I'm done with the UI changes, if that's ok with you. 

And yes, a thousand au should be more than fine 😄 Only scenario that gets close to that is the Planet Nine one... The galaxy simulation plays out within an astronomical unit 🤣 As long as you keep the masses of the bodies being simulated proportional to the distances involved it all works out well

**Comment by HugoGranstrom** [comment]
👍👌 sounds excellent 😉 

Sounds like I was worried without need 😅 it could be a funny bug in the future if we created a super sized simulation and then all of a sudden everything stops working because a planet went out of bounds 😂 I'm feeling like I need my beauty sleep now :rofl :sleeping:

**Comment by TheHappyKoala** [comment]
Hahahaha... It's all working beautifully, so yea, nothing to worry about! Can't wait to try this out on the structure formation scenario... But yea, that will be like an easter egg for people to discover, if the simulation breaks because the bounds of the simulation were exceeded 🤣 ! 

I need to zzzZZzzzZZzzz, too... Sleep tight and happy Friday!

**Comment by HugoGranstrom** [comment]
Tried out the sliders today and if you look really close you can see the shift in speed but it's rather subtle. Raising theta too high gives some funny behaviors like the moon of Jupiter leaving orbit 🤣 

That's a way at looking at it 😆 They flew to close (far away) to the sun then 🐦 🚀 🤣 .

**Comment by TheHappyKoala** [comment]
Hahaha... Oh, the poetry of it all! 

Haven't read through all the code yet so I have a quick question: has the softening constant been implemented for BH??? 

I'm rewriting the particle engine as I write this so that by setting a withMass prop to true all particles will feel the gravity of all the other particles... mehehehe! 

As for the Theta slider, let me know if the 0 - 5 value range does the trick or if I should enable higher values... Although I'm always wary about giving users too much power over the Universe :P

**Comment by HugoGranstrom** [comment]
No, I forgot to add it in all the excitement 😅 but it is a quick fix. I just need to change one line of code, in combination with my other pull request. I'll add it to that one right away.

Will it automatically activate when BH is turned on or is it up to the user to choose whether or not to use massive particles? 

I would rather lower it 😂 at 2 it starts to freak out already so I can't imagine why anyone would use 5. But some power over the universe is always nice to have the illusion of 😉

**Comment by TheHappyKoala** [comment]
The goal is basically for a user to be able to fry their fancy gaming laptop by toggling the withMasses property when running, for example, the Earth VS. the Rings of Saturn simulation, but to start with it will be limited to a specific scenario type that won't allow for the simulation of masses that are represented by meshes as opposed to sprites. But no, I don't think it should be activated when BH turns on... I like the idea of giving the user granular control... Or do you think I'm creating a user interface with a bunch of controls that people will never play with? These decisions are hard to make sometimes. 

Sweet, I'll do a git pull once the fix is up!

**Comment by HugoGranstrom** [comment]
Now when I think about it a bit more, I realize I was a bit narrow-minded 😅 For some reason I thought people would only turn it on when doing large simulation (and use BH as well), but I can see situations where that wouldn't necessarily be the case. 

So follow your motto: Freedom! 🗽

**Pull request merged**
