### PR TITLE
add SOI-stuff

### PR DESCRIPTION
**Pull request by HugoGranstrom**
After a few days of silence, I'm back 😅 
What I've done here is adding two (exported) functions:
- `constructSOITree(masses: Array<MassType>): SOITree` , which constructs our tree data structure from the list of masses (scenario.masses in most cases).
- `findCurrentSOI(pos: MassType, tree: SOITree, masses: Array<MassType>): MassType` , which checks which body's SOI, pos is in. 
Exemple of usage: construct the tree once at the beginning of the simulation (if things are just orbiting each other). We will have to reconstruct it when bodies collide or are created. If we want to know which SOI a spacecraft is in we just call `findCurrentSOI(spacecraft, tree, scenario.masses)` and we will get the body. 

One thing I suggested isn't implemented yet, namely which SOIs we are passing through/which pertrubators we should choose. The dilemma is that they aren't the same. I see no problem in implementing both, I would like to know how you want to use them though. So I can tailor them for it.

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Sweet! Gonna read through it and get back to you once I've figured out how to implement it gui wise. If you have any ideas in mind already, blurt them out and we'll go with that 🚀

**Comment by HugoGranstrom** [comment]
Feels like I could do it in 101 different ways 🤣 so I think it's best that you, who will use them the most, decide on it 😅 just give me a function signature or two and I will try to make ot happen 😉

**Comment by TheHappyKoala** [comment]
Aight, I'll conjure something, then 😄

**Comment by HugoGranstrom** [comment]
While I'm at it I added the last functions to `planFlight`

**Pull request merged**
