### PR TITLE
Inital Lambert solver

### PR DESCRIPTION
**Pull request by HugoGranstrom**
I haven't put the Lambert solver to use anywhere in the code yet so for now it's just a file. fixed my cross product mistake as well. Not quite ready for merge yet, just wanted to know my work won't be deleted by a failing hard drive or something 🤣

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Awesome stuff! And yes, committing small and often is the way to go... Hms, I should take that to heart 🤔

**Comment by TheHappyKoala** [comment]
Ah, damn, I got so enthousiastic I didn't read the not ready for merge part before MERGING it 🤣

**Comment by TheHappyKoala** [comment]
Do bear with me, I'm horrible

**Comment by TheHappyKoala** [comment]
Ah, no! I didn't click the merge button

**Comment by TheHappyKoala** [comment]
Still, made myself look like the fool that I am with the comments above

**Comment by HugoGranstrom** [comment]
Then I'll do it 🤣 It doesn't really interfere with anything else so why not. I will just have a hard time using ypu new cool stuff and this together otherwise 😅😵🤣

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
