### PR TITLE
add log-spaced dts for arrow buttons

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Here's my implementation. I tested it on a few scenarios and it seems to work, although the max/minDt for many scenarios isn't optimal at the moment. The slowest is too slow and the fastest is too fast.

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Looks super nice! Yea, the minDt and maxDt values need to be changed for most scenarios, indeed. I'll take care of that. Feel free to merge away if you feel like it's good to go 🚀

**Comment by HugoGranstrom** [comment]
Thanks 😄 I'll sleep on it and merge it tomorrow unless a better alternative comes to mind

**Comment by TheHappyKoala** [comment]
@HugoGranstrom Any chance you could merge this guy into the UI branch that I created the other day? So that it goes out with all the scenarios having proper minDt and maxDt values. When something is merged into master, a production build is triggered and deployed automatically.

**Comment by HugoGranstrom** [comment]
Sure, will give it a try. May the git gods have mercy on me

**Comment by HugoGranstrom** [comment]
I hope I did it right 😬

**Comment by TheHappyKoala** [comment]
Looks goodie woodie!

**Comment by HugoGranstrom** [comment]
Then I'll merge it 😱

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀 🚀 🚀 🚀

**Comment by TheHappyKoala** [comment]
Thanks!

**Pull request merged**
