### PR TITLE
create Velocity Verlet integrator

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Hi! I'm also interested in space and simulations and I think you have managed to get your simulation to look really cool ;-) My biggest interest is the integrators so I made an implementation of the Velocity Verlet integrator. It's more accurate than Euler and less resource intensive than RK4. Are you interested in having more integrators in your project? If so, I have a few others I can try to help you with as well. 

Have a nice day :-)

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Hej hopp, Hugo!

Snyggt jobbat! 

Fact of the matter is that I'm super keen on having additional integrators implemented. One of the reasons is that not everybody is in possession of a device powerful enough to run a simulation of a lot of bodies with an RK4 integrator, and another is that collisions don't work very well with a fixed time step. Not sure you've browsed the issues I've listed thus far, but one of them is the need for an integrator with an adaptive time step. Is this something you would be interested in implementing? Any integrator is of course welcome, especially ones with greater accuracy, but I believe in providing users with, ehrm, integrator choice, as opposed to consumer choice? We don't live in communist Russia where everybody has to use the same integrator, after all! 

Would you like to be listed in the credits for your contribution? I'm also planning on adding a section in the readme for contributors... There are some guidelines for how to do that, but I never get around to it, but I really should and have to :D! 

And thanks for the compliment, and welcome to the project :D!!!

**Comment by HugoGranstrom** [comment]
Thank you, I agree with you, choices are good. I'll continue this discussion in the issue. 

It would be an honor to be listed in the credits and I hope I can bring more to the table in the future. 

Keep up the good work :-D

**Comment by TheHappyKoala** [comment]
I'm sure you can, given that you're a student of physics! Added a credits section to the readme with you in it. If you would like me to link to another page than your personal website, let me know and I'll take care of that. 

The Verlet integrator will be pushed online with the next build, alongside a mention of yourself in the credits section. 

Also... I hate asking, but could you give the repository a star? Wouldn't care if it wasn't for the fact that projects with more stars bring more interest, and as I want this to be an inclusive venture where as many awesome people as possible bring their know-how to the table, that is something I do care about :D!

**Comment by HugoGranstrom** [comment]
Awesome! :-D looks really cool (I like the :rocket: especially). That is much more than I expected, I better start writing some more blog post again... XD. 

I thought I had already done it but apparently not :/ of course you deserve a star ;-)

**Pull request merged**
