### PR TITLE
Add rkn12

### PR DESCRIPTION
**Pull request by HugoGranstrom**
It has arrived!🔥 I won't spoil anything about it, test it and enjoy 😉

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀 🚀 🚀 !!!! 

Gonna give it a test drive now 😄 I just pushed the ui changes you suggested for the physics tab; please let me know if it looks ok to you ui wise and whether the values I picked give you too much or too little freedom in configuring the time step 🕐🕐🕐🤣  for adaptive integrators. 

How did the exams go? Make sure to treat yourself to something... I'd always spoil myself a bit when I was done with my exams... Oh, memories 💭 🤔 ⏳ 

I'm gonna sit down tomorrow night and try to make a list of priorities, because I have so many features and so on that are half done and I need to learn to focus a little bit... I'm like a little puppy who's just chasing his own tail and getting interested in whatever pops up 🐶 🐕 🐩 🤣 

Anyhow, please let me know about the latest ui features if it's what you had in mind, and super thank you for your latest integrator... Wouldn't be too surprised if eventually you'll add your very own XWARP-Granström Greater than All Integrators that Came Before It Integrator (XGGAICBI) 😄 🚀 

Okay, gonna have some fun with the RKN12 now 🐴 🏇

**Comment by TheHappyKoala** [comment]
Ooops, need to enable the dt controls for the RKN12 integrator ✈️

**Comment by TheHappyKoala** [comment]
😮 😮 😮 😮 😮 😮 🚀  🚀  🚀  🚀  🚀  🚀  🚀  🚀 

Holy mother of God that integrator is powerful!!! I'm gonna have to revise the default tolerance, max and min delta time values... Ran it with the free return trajectory scenario and basically it almost kept the highest allowed dt value throughout the whole simulation; only when it swung around the Moon did dt drop ever so slightly: needless to say, RKN12 is the new default integrator 😄 🏅 

Gonna look into the defaults tomorrow alongside my prio list (see, point in case, I'm already turning my attention elsewhere 🤣, but I feel that this time it's justified!!!). 

Can't wait to sit down and properly test the power of this beast come the weekend... 

Oh, and I just pushed a build where the RKN12 is the default integrator and you can toggle the advanced time step controls for it, too, in the physics tab.

I'll update the credits component with your latest achievements, as well, tomorrow! My apologies for not having updated it lately, but you produce them integrators so fast I can barely keep up with you 🚀 🚀 🚀

**Comment by HugoGranstrom** [comment]
The UI is exactly like I pictured it 😉 The value range seems good as well, it can't really do that much harm if you raise the maxDt as long as you keep a low error tolerance.

The exams went relatively well, ironically enough it was the physics exam that went the worst 🤣 

Haha we'll see about that 🤣 but if I do I will definitely name it XGGAICBI 😉 

RKN12 truly is a force to be reckoned with, maybe it was unwise to let it loose in the world 😆 🚀 💨

**Pull request merged**
