### PR TITLE
[Unfinished] add softening factor to brute force

### PR DESCRIPTION
**Pull request by HugoGranstrom**
As I've said, I'm new to Typescript so this may not be perfect code 😅 but if it works as intentioned you should now be able to pass a softening factor to the integrator. 

Wait 'til you have implemented the UI before you merge this, it may or may not freeze the time of the universe 🤣

### CODE REVIEW

**Comment by TheHappyKoala** [comment]
Excellent!!! And yes, so far you're excelling at TypeScript 😄!

I'll implement the UI and then merge this branch once I've cobbled together the structure formation scenario. From my understanding structure formation is not that difficult to simulate as far as the initial conditions go as the distribution of matter was smoother than a baby's ass, but said baby's ass did have a pimple or two, read over-densities, and these over-densities, although insanely small deviations are what led to the large scale structures comprised of galaxies, clusters and super clusters that we see today... So I'll just write a cheap ass method that generates a sphere of particles where some of them are only ever so slightly more massive than the rest, and then we'll see how that pans out... Then we can look into making a tad bit more sophisticated, if need be, but for now I just want something to test bh on 🤣

**Comment by HugoGranstrom** [comment]
Puh... 😌 What a relief.

That's true ;-) I'm aiming on getting it up and running by tomorrow evening (which means next week 😅 if against all odds it works on the first try 🤣 ).

**Comment by HugoGranstrom** [comment]
I think this fixed it, the commit became a bit circular 😅 I had to merge BH into this branch to add the softening to it. Now when I look at it in hindsight I should just have created a new pull request with just this change...

**Comment by TheHappyKoala** [comment]
Nice... I'm going to do what I always do when I get stuck... Browse wikipedia, fall asleep and wake up and kick some serious ass... I think some super being decided to run the When Galaxies Collide scenario with the withMass property set to true, with my brain as the processing unit... Which is to say my brain has decided to shut down for today 🤣 

I'll ping you when I've hopefully been able to get something fancy pancy online, which should be tomorrow 🚀 🗽 🇺🇸

**Pull request merged**
